import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'
import { cn } from '@app/lib/utils'
import ReactQueryClientProvider from '@app/components/ReactQueryClientProvider'
import { Toaster } from '@app/components/ui/toaster'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import StyledComponentsRegistry from '@app/lib/registry'
import ThemeProvider from '@app/components/ThemeProvider'

import { GeistMono } from 'geist/font/mono'
import { GeistSans } from 'geist/font/sans'

// const fontSans = FontSans({
//   subsets: ['greek'],
//   variable: '--font-sans'
// })

const fontSans = GeistSans

const fontMono = GeistMono

export const metadata: Metadata = {
  title: 'KMAPP Solutions',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages()

  return (
    <html lang={locale} suppressHydrationWarning>
      <ReactQueryClientProvider>
        <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable, fontMono.variable)}>
          <NextIntlClientProvider messages={messages}>
            <StyledComponentsRegistry>
              <ThemeProvider storageKey={'theme'} attribute='class' defaultTheme='system'>
                {children}
                <Toaster />
                <ToastContainer />
              </ThemeProvider>
            </StyledComponentsRegistry>
          </NextIntlClientProvider>
        </body>
      </ReactQueryClientProvider>
    </html>
  )
}
