import { ListingQuery } from '@app/api'
import { AutoGenerateDailyReportQueries } from '@app/containers/Plans/types/plan.types'

export const dailyReportQueryKey = {
  getAllDailyReports: (query?: ListingQuery) => ['get-all-daily-reports', query],
  autoGenerateDailyReport: (queries: AutoGenerateDailyReportQueries) => ['get-auto-generate-daily-reports', queries],
  getDailyReport: (id: string) => ['get-daily-report', id]
}
