import { useQuery } from '@tanstack/react-query'
import callApi from '@app/api/apiCaller'
import { DataEntry, KMAPP_ENDPOINT } from '@app/api'
import { DailyReport } from '@app/containers/DailyReports/types/daily-report.types'
import { dailyReportQueryKey } from '@app/containers/DailyReports/constants/daily-report.query-key'
import { AutoGenerateDailyReportQueries } from '@app/containers/Plans/types/plan.types'

const useAutoGenerateDailyReport = ({ employeeId, date }: AutoGenerateDailyReportQueries) => {
  return useQuery({
    queryKey: dailyReportQueryKey.autoGenerateDailyReport({ date, employeeId }),
    queryFn: async () => {
      return await callApi<DataEntry<DailyReport, true>, AutoGenerateDailyReportQueries>(
        `${KMAPP_ENDPOINT.dailyReport}/auto/date-employee`,
        'get',
        undefined,
        {
          employeeId,
          date
        }
      )
    },
    enabled: !!employeeId
  })
}

export default useAutoGenerateDailyReport
