import { Typography } from '@app/components/ui/typography'
import { Button } from '@app/components/ui/button'
import { SaveIcon, Sparkles, Trash2Icon, XIcon } from 'lucide-react'
import { useParams, useRouter } from 'next/navigation'
import { DefaultValues, useForm } from 'react-hook-form'
import { Form } from '@app/components/ui/form'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
import ConfirmDialog from '@app/components/ConfirmDialog'
import React, { useEffect, useState } from 'react'
import FormField from '@app/components/Form/FormField'
import { useQueryClient } from '@tanstack/react-query'
import BackDrop from '@app/components/BackDrop/BackDrop'
import useDeleteDailyReports from '@app/containers/DailyReports/hooks/useDeleteDailyReports'
import useCreateDailyReport from '@app/containers/DailyReports/hooks/useCreateDailyReport'
import { DAILY_REPORT_LIST_ROUTE } from '@app/containers/DailyReports/constants/daily-report-routes.constants'
import useGetDailyReport from '@app/containers/DailyReports/hooks/useGetDailyReport'
import { generateMultiSelectOptions } from '@app/utils/generateSelectOptions'
import useUpdateDailyReport from '@app/containers/DailyReports/hooks/useUpdateDailyReport'
import { dailyReportQueryKey } from '@app/containers/DailyReports/constants/daily-report.query-key'
import { toast } from 'react-toastify'
import { dailyReportSchema } from '@app/containers/DailyReports/constants/daily-report.schemas'
import DatePicker from '@app/components/DatePicker'
import useGetEmployees from '@app/containers/Employees/hooks/useGetEmployees'
import MultiSelectHook from '@app/components/Form/MultiSelectHook/MultiSelectHook'
import PageFooter from '@app/components/Page/PageFooter'
import ProducingInfo from '@app/containers/DailyReports/DailyReportDetail/components/ProducingInfo'
import IssueProducts from '@app/containers/DailyReports/DailyReportDetail/components/IssueProducts'
// import ReturnMaterial from '@app/containers/DailyReports/DailyReportDetail/components/ReturnMaterials'
import { Separator } from '@app/components/ui/separator'
import PageContent from '@app/components/Page/PageContent'
import { Employee } from '@app/containers/Employees/types/employee.types'
import useAutoGenerateDailyReport from '@app/containers/DailyReports/hooks/useAutoGenerateDailyReport'
import Tooltip from '@app/components/Tooltip'
import useGetEmployeeTickets from '@app/containers/TicketPlanning/hooks/useGetEmployeeTickets'
import Combobox from '@app/components/Combobox'
type FormFields = z.infer<typeof dailyReportSchema>

const defaultValues: DefaultValues<FormFields> = {
  issueProducts: [],
  date: undefined,
  producingInfos: [],
  reportEmployee: undefined,
  // returnMaterials: [],
  tickets: [],
  workingEmployee: undefined
}

const DailyReportDetail = () => {
  const { id } = useParams()
  const isEdit = !!id
  const router = useRouter()
  const queryClient = useQueryClient()

  const form = useForm<z.infer<typeof dailyReportSchema>>({
    resolver: zodResolver(dailyReportSchema),
    defaultValues: {
      ...defaultValues
    }
  })

  const {
    handleSubmit,
    reset,
    setValue,
    watch,
    formState: { isDirty },
    getValues
  } = form

  const selectedWorkingEmployee = watch('workingEmployee') as Employee
  const selectedDate = watch('date')

  const { mutate: mutateDeleteDailyReports, isPending: isDeletingDailyReports } = useDeleteDailyReports()
  const { mutate: mutateCreateDailyReport, isPending: isCreatingDailyReport } = useCreateDailyReport()
  const { mutate: mutateUpdateDailyReport, isPending: isUpdatingDailyReport } = useUpdateDailyReport()

  const [openDialogDelete, setOpenDialogDelete] = useState(false)
  const onSubmit = (values: z.infer<typeof dailyReportSchema>) => {
    if (isEdit) {
      mutateUpdateDailyReport(
        {
          ...values,
          id: id as string
        },
        {
          onSuccess: async () => {
            toast.success(`Update report successfully`)
            await queryClient.invalidateQueries({ queryKey: [dailyReportQueryKey.getDailyReport(id as string)[0]] })
            await queryClient.invalidateQueries({ queryKey: [dailyReportQueryKey.getAllDailyReports()[0]] })
          }
        }
      )
    } else {
      mutateCreateDailyReport(
        {
          ...values
        },
        {
          onSuccess: async () => {
            toast.success(`Create daily report successfully`)
            router.push(DAILY_REPORT_LIST_ROUTE)
            await queryClient.invalidateQueries({ queryKey: [dailyReportQueryKey.getAllDailyReports()[0]] })
          }
        }
      )
    }
  }
  const handleDelete = () => {
    mutateDeleteDailyReports(
      { id: [id as string] },
      {
        onSuccess: async () => {
          toast.success(`Delete report successfully`)
          router.push(DAILY_REPORT_LIST_ROUTE)
          await queryClient.invalidateQueries({ queryKey: [dailyReportQueryKey.getAllDailyReports()[0]] })
        }
      }
    )
  }
  const { data: generatedDailyReport, isLoading: isGeneratingDailyReport } = useAutoGenerateDailyReport({
    date: selectedDate || '',
    employeeId: selectedWorkingEmployee?.id || ''
  })

  const handleGenerateDailyReport = () => {
    if (generatedDailyReport?.data) {
      const { issueProducts, reportEmployee, workingEmployee, producingInfos, tickets } = generatedDailyReport.data

      reset({
        issueProducts,
        reportEmployee,
        // returnMaterials,
        producingInfos,
        tickets,
        date: selectedDate
      })
      setValue('workingEmployee', workingEmployee, { shouldDirty: true })
    }
  }

  const { data: employees, isLoading: isGettingEmployees } = useGetEmployees({})
  const { data: tickets, isLoading: isGettingTickets } = useGetEmployeeTickets({})
  const employeeOptions = generateMultiSelectOptions({
    data: employees?.data,
    labelKey: 'name',
    renderLabel: (item: Employee) => `${item.name} - ${item.group.name}`,
    valueKey: 'id',
    valueAsObject: true
  })
  const ticketOptions = generateMultiSelectOptions({
    data: tickets?.data,
    labelKey: 'id',
    valueKey: 'id',
    valueAsObject: false
  })

  const { data: dailyReport, isLoading: isGettingDailyReport } = useGetDailyReport({ id: id as string })

  useEffect(() => {
    if (dailyReport?.data) {
      const { issueProducts, reportEmployee, workingEmployee, producingInfos, tickets, date } = dailyReport.data

      reset({
        issueProducts,
        reportEmployee,
        workingEmployee,
        // returnMaterials,
        producingInfos,
        tickets,
        date
      })
    }
  }, [dailyReport, isEdit, tickets, employees])

  return (
    <Form {...form}>
      <BackDrop isLoading={isGettingDailyReport || isGettingEmployees || isGettingTickets} />
      <form onSubmit={handleSubmit(onSubmit)} className='h-full flex flex-col justify-between'>
        <PageContent>
          <div className='mb-4'>
            <Typography variant='h3'>
              {isEdit ? `Edit daily report ${dailyReport?.data?.id}` : 'Create daily report'}
            </Typography>
          </div>
          <div>
            <div className='flex flex-col gap-2 w-full desktop:w-1/4'>
              <FormField
                control={form.control}
                name='date'
                label={'Date'}
                renderComponent={({ field }) => (
                  <DatePicker
                    value={field?.value ? new Date(field.value) : undefined}
                    onChange={(date) => {
                      field.onChange(date?.toISOString())
                    }}
                  />
                )}
              />
              <FormField
                control={form.control}
                name={`tickets`}
                label={'Tickets'}
                renderComponent={({ field }) => (
                  <MultiSelectHook<string>
                    value={field.value}
                    onChange={field.onChange}
                    options={ticketOptions}
                    placeholder='Select tickets id'
                  />
                )}
              />
              <FormField
                control={form.control}
                name={`reportEmployee`}
                label={'Reported Employee'}
                renderComponent={({ field }) => (
                  <Combobox
                    {...field}
                    onValueChange={field.onChange}
                    options={employeeOptions}
                    valueKey={'id'}
                    placeholder='Select reported employee'
                  />
                )}
              />
              <FormField
                control={form.control}
                name={`workingEmployee`}
                label={
                  <div className='flex gap-2 items-center'>
                    <div>Working employee</div>
                    <div>
                      <Tooltip popupContent={'Generate report'}>
                        <Button
                          variant='ghost'
                          className='p-1 h-auto rounded-full'
                          onClick={handleGenerateDailyReport}
                          disabled={!selectedWorkingEmployee || !selectedDate}
                        >
                          <Sparkles size={14} />
                        </Button>
                      </Tooltip>
                    </div>
                  </div>
                }
                renderComponent={({ field }) => (
                  <Combobox
                    {...field}
                    onValueChange={field.onChange}
                    options={employeeOptions}
                    valueKey={'id'}
                    placeholder='Select working employee'
                  />
                )}
              />
            </div>
            <div className='w-full desktop:w-1/2'>
              <div className='mt-8 mb-4'>
                <ProducingInfo />
              </div>
              <Separator />
              <div className='mt-4 mb-4'>
                <IssueProducts />
              </div>
              {/*<Separator />*/}
              {/*<div className='mt-4 mb-4'>*/}
              {/*  <ReturnMaterial />*/}
              {/*</div>*/}
            </div>
          </div>
        </PageContent>
        <PageFooter>
          <div className='flex gap-4'>
            {isEdit && (
              <Button
                variant='destructive'
                color='red'
                isLoading={isCreatingDailyReport || isDeletingDailyReports || isUpdatingDailyReport}
                onClick={() => setOpenDialogDelete(true)}
              >
                <Trash2Icon className='mr-2' />
                DELETE
              </Button>
            )}
            <Button
              isLoading={isCreatingDailyReport || isDeletingDailyReports || isUpdatingDailyReport}
              disabled={!isDirty || isCreatingDailyReport || isDeletingDailyReports || isUpdatingDailyReport}
              type='submit'
            >
              <SaveIcon className='mr-2' />
              SAVE
            </Button>
          </div>
        </PageFooter>
        <ConfirmDialog
          open={openDialogDelete}
          onClose={() => setOpenDialogDelete(false)}
          onConfirm={() => handleDelete()}
          onReject={() => setOpenDialogDelete(false)}
          dialogTitle={'Delete Items'}
          confirmMessage='Do you want delete this items ?'
        />
      </form>
    </Form>
  )
}

export default DailyReportDetail
