export const KMAPP_ENDPOINT = {
  order: 'order',
  planning: 'planning',
  planDetail: 'planning-detail',
  machine: 'machine',
  recipe: 'recipe',
  product: 'product',
  productType: 'product-type',
  process: 'process',
  stage: 'stage',
  productionQuota: 'production-quota',
  tool: 'tool',
  department: 'department',
  employee: 'employee',
  employeeGroup: 'group',
  position: 'position',
  customer: 'customer',
  productIssue: 'product-issue',
  dailyReport: 'report/daily',
  ticket: 'ticket',
  employeeTicket: 'employee-ticket',
  dashboard: 'dashboard',
  file: 'file',
  security: 'security',
  role: 'role',
  user: 'user'
}
